### ISSUE TITLE
add semantic scholar search backend

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/pysotsog#32]
e.g. using 
- https://github.com/danielnsilva/semanticscholar
- https://github.com/mirandrom/PyS2

for e.g.
https://api.semanticscholar.org/api-docs/graph#tag/Paper-Data/operation/get_graph_get_paper_search

**Comment by tholzheim** [comment]
Wikidata currently has `40619` humans with the [Semantic Scholar author ID](https://www.wikidata.org/wiki/Property:P4012)
```sparql
SELECT (COUNT(DISTINCT ?id) as ?count) 
WHERE 
{
  ?author wdt:P31 wd:Q5;
          wdt:P4012 ?id.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } # Helps get the label in your language, if not, then en language
}
```
[Try it](https://query.wikidata.org/#SELECT%20%28COUNT%28DISTINCT%20%3Fid%29%20as%20%3Fcount%29%20%0AWHERE%20%0A%7B%0A%20%20%3Fauthor%20wdt%3AP31%20wd%3AQ5%3B%0A%20%20%20%20%20%20%20%20%20%20wdt%3AP4012%20%3Fid.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%20%23%20Helps%20get%20the%20label%20in%20your%20language%2C%20if%20not%2C%20then%20en%20language%0A%7D)
