### ISSUE TITLE
Manual Python build lacks binary

### ISSUE THREAD

**Issue by meerfrau** [WolfgangFahl/pysotsog#52]
I've built pysotsog with
```
	python -m build --wheel --no-isolation
	python -m installer --destdir="$pkgdir" dist/*.whl
```
and I'm getting a structure
```
    └── usr
        └── lib
            └── python3.10
                └── site-packages
                    ├── skg
                    │   ├── citeproc.py
```
but where is the binary to run ./pysotsog ?

**Comment by WolfgangFahl** [comment]
https://wiki.bitplan.com/index.php/Pysotsog#Installation shows the proper procedure. I wonder why you tried "something completly different". Your approach looks quite awkward.

After the pip install you can try to find where the command line tool (ther is not really such a thing as a "binary" since thi is python) is located with
```bash
which sotsog
/Users/wf/Library/Python/3.10/bin/sotsog
```

and try the usage with
```bash
sotsog -h

usage: sotsog [-h] [--about] [--bibtex] [-d] [--host HOST] [-la LANG] [-li LIMIT] [-nb] [--port PORT]
              [--scite] [--smw] [--serve] [--wikiId WIKIID] [-V]
              [search ...]

sotsog: Standing on the shoulders of giants - with direct access to the clouds

  Created by Wolfgang Fahl on 2022-11-16.
  Copyright 2022 Wolfgang Fahl. All rights reserved.

  Licensed under the Apache License 2.0
  http://www.apache.org/licenses/LICENSE-2.0

  Distributed on an "AS IS" basis without warranties
  or conditions of any kind, either express or implied.

USAGE

positional arguments:
  search                search terms

options:
  -h, --help            show this help message and exit
  --about               show about info
  --bibtex              output bibtex format
  -d, --debug           show debug info
  --host HOST
  -la LANG, --lang LANG
                        language code to use
  -li LIMIT, --limit LIMIT
                        limit the number of search results
  -nb, --nobrowser      do not open browser
  --port PORT
  --scite               output #scite format
  --smw                 output Semantic MediaWiki (SMW) format
  --serve               start webserver
  --wikiId WIKIID       the id of the SMW wiki to connect with
  -V, --version         show program's version number and exit
```

Feel free to contact me e.g. via LinkedIn to discuss more details.

**Comment by meerfrau** [comment]
I'm using many no-tracking browser addons and because of them LinkedIn is asking me for Captcha verification or kicking me straight out.

> Your approach looks quite awkward.
I simply [don't like](https://xkcd.com/1987/) virtual envs and package everything into my distro's format.

You could help me enormously if you'd upload the _pysotsog_ binary somewhere.

**Comment by WolfgangFahl** [comment]
Just use the public demo http://sotsog.bitplan.com/ in this case. 
_I simply [don't like](https://xkcd.com/1987/) virtual envs_ which is a pitty since these envs make life so much simpler. I don't offer sotsog as a paid service.

**Comment by meerfrau** [comment]
> You could help me enormously if you'd upload the _sotsog_ binary somewhere.
Sie wären mir sehr verbunden und ich würde sie nie wieder behelligen.

**Comment by meerfrau** [comment]
```
#!$env/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from skg.sotsog import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
